### ISSUE TITLE
Confusion around NA-N1 segment

### ISSUE THREAD

**Issue by molly-hetheringtonrauth** [treangenlab/InfA-amplicon#1]
The confusion arises because there are two viruses with the NA-N1 segment - H5N1 and H1N1.

In the bed file there are 5 unique references:
- H5N1-HA
- H1N1-HA
- H3N2-HA
- H3N2-NA
**- H5N1-NA**

However there are 7 unique reference sequences:
- H3N2 2022-05-25 HA consensus.fasta
**- H1N1 2022-05-25 NA consensus.fasta**
- H1N1 2022-05-25 HA consensus.fasta
- H5N1 2022-05-25 HA consensus.fasta
**- H1N1 2024-01-20 H5N1 2022-05-25 NA consensus.fasta**
**- H5N1 2022-05-25 NA consensus.fasta**
- H3N2 2022-05-25 NA consensus.fasta

The sequences for **- H1N1 2022-05-25 NA consensus.fasta**, **- H1N1 2024-01-20 H5N1 2022-05-25 NA consensus.fasta**, and **- H5N1 2022-05-25 NA consensus.fasta** don't appear to be the same. 

Which consensus sequence should be used as the reference sequence for read mapping that corresponds to the H5N1-NA reference primer positions in the bed file. I'm assuming its the **- H5N1 2022-05-25 NA consensus.fasta** but want to confirm.

**Comment by mxwang66** [comment]
Hi @molly-hetheringtonrauth, 

Sorry for the late response! `H1N1 2024-01-20 H5N1 2022-05-25 NA consensus.fasta` is generated using the NA segments of both H1N1 and H5N1, but the mutation density of the MSA seemed to be too high (see page 5 of README.pdf). Since we were trying to focus on H5N1 at that time, we decided to only design primers for the NA segment of H5N1. We were worried that if the NA segments of H1N1 and H5N1 were designed separately, the primers might form dimers. In other word the NA segment of H1N1 is left out for design, so there are only 5 unique references but 7 consensus sequences were made. 

However, it's been a few months since these consensus sequences were made, I would suggest downloading the latest sequences from GISAID. I recently made a tool to generate consensus and do variant calling with an MSA, and you might find it useful: https://github.com/mxwang66/olivar-validate

Best regards, 
Michael
